package com.alphadevelopmentsolutions.frcscout.Interfaces

interface StatsKeys
{
    companion object
    {
        val MIN = "MIN"
        val MAX = "MAX"
        val AVG = "AVG"

        val AUTO_EXIT_HAB = "AUTO_EXIT_HAB"
        val AUTO_HATCH = "AUTO_HATCH"
        val AUTO_HATCH_DROPPED = "AUTO_HATCH_DROPPED"
        val AUTO_CARGO = "AUTO_CARGO"
        val AUTO_CARGO_DROPPED = "AUTO_CARGO_DROPPED"
        val TELEOP_HATCH = "TELEOP_HATCH"
        val TELEOP_HATCH_DROPPED = "TELEOP_HATCH_DROPPED"
        val TELEOP_CARGO = "TELEOP_CARGO"
        val TELEOP_CARGO_DROPPED = "TELEOP_CARGO_DROPPED"
        val RETURNED_HAB = "RETURNED_HAB"
        val RETURNED_HAB_FAILS = "RETURNED_HAB_FAILS"
        val DEFENSE_RATING = "DEFENSE_RATING"
        val OFFENSE_RATING = "OFFENSE_RATING"
        val DRIVE_RATING = "DRIVE_RATING"

        val STATS_CATEGORY_ORDER_KEYS = arrayOf(MIN, AVG, MAX)

        val STATS_ORDER_KEYS = arrayOf(AUTO_EXIT_HAB, AUTO_HATCH, AUTO_HATCH_DROPPED, AUTO_CARGO, AUTO_CARGO_DROPPED, TELEOP_HATCH, TELEOP_HATCH_DROPPED, TELEOP_CARGO, TELEOP_CARGO_DROPPED, RETURNED_HAB, RETURNED_HAB_FAILS, DEFENSE_RATING, OFFENSE_RATING, DRIVE_RATING)
    }
}
